on:
  push:
    branches: main
  schedule:
    - cron: '30 23 * * *'

name: Update Website

jobs:
  website:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Build website
        run: Rscript -e 'source("make.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Update website' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
